version: '3.3'
services:
    app:
        image: michaelpc/openshift:latest
        working_dir: /app/src
        volumes:
            - ./src:/app/src
            - cpanfiles:/app/cpanfiles
        environment:
            - IF_IN_RUN_0000000020=00
            - IF_IN_RUN_0000000100=00
            - OTHER_CPANFILES=/app/src/cpanfile
            - PERL_CARTON_PATH=/app/cpanfiles
            - DEBUG_RESPONSE_IF_FAIL=1
            - DEBUG_IN_OUT=0
            - DEBUG_SEND_OUT=0
            - DEBUG_RESPONSE=0
            - DEBUG_RESPONSE_HEADER_ONLY=0
            - RETRY_FAIL_RESPONSE=5
            - RETRY_DELAY=5
volumes:
    cpanfiles:
